var xImpresoraPrint,_numIntCorrelativoBD;async function xCocinarImprimirComprobante(xArrayCuerpo,xArraySubTotales,xArrayComprobante,xArrayCliente,idregistro_pago,xidDoc,showPrint=true){let rptPrint={}
if(!!xArrayComprobante){if(xArrayComprobante.idtipo_comprobante==="0"){rptPrint.imprime=false;return rptPrint;}}else{rptPrint.imprime=false;return rptPrint;}
if(showPrint){if(!xgetComprobanteImpresora(xidDoc)){rptPrint.imprime=false;}}
if(xArrayCuerpo.length==0){rptPrint.imprime=false;rptPrint.ok=false;rptPrint.msj='Los datos del comprobante no son correctos.';return rptPrint;}
var xArrayEncabezado=xm_log_get('datos_org_sede');xArraySubTotales=darFormatoSubTotalesParaFacturacion(xArraySubTotales,false);const index_total=xArraySubTotales.length-1;const total_pagar=parseFloat(xArraySubTotales[index_total].importe);xArraySubTotales[index_total].importe_letras=numeroALetras(total_pagar);if(showPrint){xArrayComprobante.pie_pagina_comprobante=xImpresoraPrint[0].pie_pagina_comprobante;}
if(xArrayComprobante.codsunat!=="0"){xm_all_xToastOpen("Conectando con Sunat...");}
const _viene_facturador=typeof idregistro_pago==="object"?true:false;_numIntCorrelativoBD=parseInt(xArrayComprobante.correlativo);const _isNotIntNumComprobante=isNaN(_numIntCorrelativoBD);if(!xArrayComprobante.correlativo||xArrayComprobante.correlativo===''||_viene_facturador||xArrayComprobante.correlativo==='#'||_isNotIntNumComprobante||_numIntCorrelativoBD==0){const numComprobante=await xGetCorrelativoComprobante(xArrayComprobante);xArrayComprobante.correlativo=numComprobante;_numIntCorrelativoBD=numComprobante;}
rptPrint=await xJsonSunatCocinarDatos(xArrayCuerpo,xArraySubTotales,xArrayComprobante,xArrayCliente,idregistro_pago);if(!rptPrint.ok){alert(rptPrint.msj_error+". Mande a imprimir el comprobante desde Registro de pagos");xPopupLoad.close;return rptPrint;}
xArrayEncabezado[0].hash=rptPrint.hash;xArrayEncabezado[0].external_id=rptPrint.external_id;xArrayComprobante.correlativo=rptPrint.correlativo_comprobante||xArrayComprobante.correlativo;xArrayComprobante.facturacion_correlativo_api=rptPrint.facturacion_correlativo_api||xArrayComprobante.facturacion_correlativo_api;if(!showPrint){return xArrayEncabezado;}
let _isPrinterCpeVal=parseInt(localStorage.getItem('::app3_sys_print_cpe'));_isPrinterCpeVal=isNaN(_isPrinterCpeVal)?1:_isPrinterCpeVal;if(_isPrinterCpeVal===0){return xArrayEncabezado;}
xImprimirComprobanteAhora(xArrayEncabezado,xArrayCuerpo,xArraySubTotales,xArrayComprobante,xArrayCliente,function(rpt_print){if(rpt_print==false){return false;}
return true;});}
function xImprimirComprobanteAhora(xArrayEncabezado,xArrayCuerpo,xArraySubtotal,xArrayComprobante,xArrayCliente,callback){let _arrBodyComprobante=xEstructuraItemsJsonComprobante(xArrayCuerpo,xArraySubtotal,true);_arrBodyComprobante=xEstructuraItemsAgruparPrintJsonComprobante(_arrBodyComprobante);const _sys_local=parseInt(xm_log_get('datos_org_sede')[0].sys_local);xArrayEncabezado[0].nom_us=xm_log_get('app3_us').nomus;comprobarNumCorrelativoComprobante(xArrayComprobante);var xArrayTPC;try{if(xarr_tipo_pago){xArrayTPC=[];xarr_tipo_pago.map(tp=>{let _vuleto=parseFloat(tp.importe_recibido)-parseFloat(tp.importe)
const _importe_recibido=_vuleto<0?tp.importe:tp.importe_recibido;_vuleto=_vuleto<0?0:_vuleto;const _rowTPC={'id':tp.id||'1','des_tp':tp.des_tp||'Efectivo','importe':tp.importe,'importe_recibido':_importe_recibido,'importe_vuelto':_vuleto,}
xArrayTPC.push(_rowTPC);});}}catch(error){}
const _data={Array_enca:xArrayEncabezado,Array_print:xImpresoraPrint,ArrayItem:_arrBodyComprobante,ArraySubTotales:xArraySubtotal,ArrayComprobante:xArrayComprobante,ArrayCliente:xArrayCliente,ArrayTipoPago:xArrayTPC}
if(_sys_local===1){xPopupLoad.xopen();xSendDataPrintServer(_data,2,'comprobante');setTimeout(()=>{xPopupLoad.xclose();callback(false);},1000);return;}
$.ajax({type:'POST',url:'../../print/print5.php',data:{Array_enca:xArrayEncabezado,Array_print:xImpresoraPrint,ArrayItem:_arrBodyComprobante,ArraySubTotales:xArraySubtotal,ArrayComprobante:xArrayComprobante,ArrayCliente:xArrayCliente}}).done(function(dtPbd){if(dtPbd.indexOf('Error')!=-1){xPopupLoad.xclose();$("#print_error").text(dtPbd);xErrorPrint=true;dialog_erro_print.open();}else{xErrorPrint=false;xPopupLoad.titulo="Imprimiendo...";xPopupLoad.xopen();setTimeout(function(){xPopupLoad.xclose()},3000);}
return callback(xErrorPrint);});}
function xImprimirComprobanteAhoraPrintPreSelect(xArrayEncabezado,xArrayCuerpo,xArraySubtotal,xArrayComprobante,xArrayCliente,xArrImpresora,callback){xPopupLoad.titulo="Imprimiendo...";const _sys_local=parseInt(xm_log_get('datos_org_sede')[0].sys_local);xArrayEncabezado[0].nom_us=xm_log_get('app3_us').nomus;comprobarNumCorrelativoComprobante(xArrayComprobante);const _data={Array_enca:xArrayEncabezado,Array_print:xArrImpresora,ArrayItem:xArrayCuerpo,ArraySubTotales:xArraySubtotal,ArrayComprobante:xArrayComprobante,ArrayCliente:xArrayCliente}
if(_sys_local===1){xPopupLoad.xopen();xSendDataPrintServer(_data,2,'comprobante');setTimeout(()=>{xPopupLoad.xclose();callback(false);},1000);return;}
$.ajax({type:'POST',url:'../../print/print5.php',data:{Array_enca:xArrayEncabezado,Array_print:xArrImpresora,ArrayItem:xArrayCuerpo,ArraySubTotales:xArraySubtotal,ArrayComprobante:xArrayComprobante,ArrayCliente:xArrayCliente}}).done(function(dtPbd){if(dtPbd.indexOf('Error')!=-1){xPopupLoad.xclose();$("#print_error").text(dtPbd);xErrorPrint=true;dialog_erro_print.open();}else{xErrorPrint=false;xPopupLoad.titulo="Imprimiendo...";xPopupLoad.xopen();setTimeout(function(){xPopupLoad.xclose()},3000);}
return callback(xErrorPrint);});}
function xgetComprobanteImpresora(xidDoc){var xArrayImpresoras=xm_log_get('app3_woIpPrint');var xDtTipoDoc=xm_log_get('app3_woIpPrintO');var xPrintLocal=window.localStorage.getItem("::app3_woIpPrintLo");xImpresoraPrint=xm_log_get("sede_generales");const num_copias_all=xImpresoraPrint[0].num_copias;var xIpPrintDoc=xidDoc;var xpasePrint=false;for(var i=0;i<xDtTipoDoc.length;i++){if(xDtTipoDoc[i].idtipo_otro==xidDoc){xIpPrintDoc=xDtTipoDoc[i].idimpresora;break;}};if(xPrintLocal!=undefined&&xPrintLocal!=''){xPrintLocal=$.parseJSON(xPrintLocal);xImpresoraPrint[0].ip_print=xPrintLocal.ip;xImpresoraPrint[0].var_margen_iz=xPrintLocal.var_margen_iz;xImpresoraPrint[0].var_size_font=xPrintLocal.var_size_font
xImpresoraPrint[0].local=1;xImpresoraPrint[0].num_copias=xPrintLocal.num_copias;xImpresoraPrint[0].copia_local=xPrintLocal.copia_local;xImpresoraPrint[0].img64=xPrintLocal.img64;xImpresoraPrint[0].papel_size=xPrintLocal.papel_size;xpasePrint=true;}else{for(var i=0;i<xArrayImpresoras.length;i++){if(xArrayImpresoras[i].idimpresora==xIpPrintDoc){xpasePrint=true;xIpPrintDoc=xArrayImpresoras[i].ip;xImpresoraPrint[0].ip_print=xIpPrintDoc;xImpresoraPrint[0].var_margen_iz=xArrayImpresoras[i].var_margen_iz;xImpresoraPrint[0].var_size_font=xArrayImpresoras[i].var_size_font;xImpresoraPrint[0].local=0;xImpresoraPrint[0].num_copias=xArrayImpresoras[i].num_copias;xImpresoraPrint[0].copia_local=0;xImpresoraPrint[0].img64=xArrayImpresoras[i].img64;xImpresoraPrint[0].papel_size=xArrayImpresoras[i].papel_size;break;}}}
return xpasePrint;}
function xgetImpresora(xidDoc){var xArrayImpresoras=xm_log_get('app3_woIpPrint');var xDtTipoDoc=xm_log_get('app3_woIpPrintO');var xPrintLocal=window.localStorage.getItem("::app3_woIpPrintLo");xImpresoraPrint=xm_log_get("sede_generales");const num_copias_all=xImpresoraPrint[0].num_copias;const papel_size=xImpresoraPrint[0].papel_size;var xIpPrintDoc=xidDoc;var xpasePrint=false;for(var i=0;i<xDtTipoDoc.length;i++){if(xDtTipoDoc[i].idtipo_otro==xidDoc){xIpPrintDoc=xDtTipoDoc[i].idimpresora;break;}};if(xPrintLocal!=undefined&&xPrintLocal!=''){xPrintLocal=$.parseJSON(xPrintLocal);xImpresoraPrint[0].ip_print=xPrintLocal.ip;xImpresoraPrint[0].var_margen_iz=xPrintLocal.var_margen_iz;xImpresoraPrint[0].var_size_font=xPrintLocal.var_size_font
xImpresoraPrint[0].local=1;xImpresoraPrint[0].num_copias=xPrintLocal.num_copias;xImpresoraPrint[0].copia_local=xPrintLocal.copia_local;xImpresoraPrint[0].img64=xPrintLocal.img64;xImpresoraPrint[0].papel_size=xPrintLocal.papel_size;xpasePrint=true;}else{for(var i=0;i<xArrayImpresoras.length;i++){if(xArrayImpresoras[i].idimpresora==xIpPrintDoc){xpasePrint=true;xIpPrintDoc=xArrayImpresoras[i].ip;xImpresoraPrint[0].ip_print=xIpPrintDoc;xImpresoraPrint[0].var_margen_iz=xArrayImpresoras[i].var_margen_iz;xImpresoraPrint[0].var_size_font=xArrayImpresoras[i].var_size_font;xImpresoraPrint[0].local=0;xImpresoraPrint[0].num_copias=xArrayImpresoras[i].num_copias;;xImpresoraPrint[0].copia_local=0;xImpresoraPrint[0].img64=xArrayImpresoras[i].img64;xImpresoraPrint[0].papel_size=xArrayImpresoras[i].papel_size;break;}}}
const print_return=xpasePrint?xImpresoraPrint:null;return print_return;}
function xgetImpresoraById(xIdPrintSearch){var xArrayImpresoras=xm_log_get('app3_woIpPrint');var xDtTipoDoc=xm_log_get('app3_woIpPrintO');var xPrintLocal=window.localStorage.getItem("::app3_woIpPrintLo");xImpresoraPrint=xm_log_get("sede_generales");const num_copias_all=xImpresoraPrint[0].num_copias;const papel_size=xImpresoraPrint[0].papel_size;const var_size_font_tall_comanda=xImpresoraPrint[0].var_size_font_tall_comanda;var xpasePrint=false;if(xPrintLocal!=undefined&&xPrintLocal!=''){xPrintLocal=$.parseJSON(xPrintLocal);xImpresoraPrint[0].ip_print=xPrintLocal.ip;xImpresoraPrint[0].var_margen_iz=xPrintLocal.var_margen_iz;xImpresoraPrint[0].var_size_font=xPrintLocal.var_size_font
xImpresoraPrint[0].local=1;xImpresoraPrint[0].num_copias=xPrintLocal.num_copias;xImpresoraPrint[0].copia_local=xPrintLocal.copia_local;xImpresoraPrint[0].img64=xPrintLocal.img64;xImpresoraPrint[0].papel_size=xPrintLocal.papel_size;xpasePrint=true;}else{const _xArrayImpresoras=xArrayImpresoras.filter(pp=>parseInt(pp.idimpresora)==xIdPrintSearch)[0];if(_xArrayImpresoras){xpasePrint=true;xImpresoraPrint[0].ip_print=_xArrayImpresoras.ip;xImpresoraPrint[0].var_margen_iz=_xArrayImpresoras.var_margen_iz;xImpresoraPrint[0].var_size_font=_xArrayImpresoras.var_size_font;xImpresoraPrint[0].local=0;xImpresoraPrint[0].num_copias=_xArrayImpresoras.num_copias;xImpresoraPrint[0].var_size_font_tall_comanda=var_size_font_tall_comanda;xImpresoraPrint[0].copia_local=0;xImpresoraPrint[0].img64='';xImpresoraPrint[0].papel_size=_xArrayImpresoras.papel_size;}}
const print_return=xpasePrint?xImpresoraPrint:null;return print_return;}
function xCocinarImprimirComanda(xArrayEnca,xArrayCuerpo,xArraySubTotales,callback){if(xArrayCuerpo.length===0)return;var xArrayImpresoras=xm_log_get('app3_woIpPrint');var xDtTipoDoc=xm_log_get('app3_woIpPrintO');var xPrintLocal=window.localStorage.getItem("::app3_woIpPrintLo");var xImpresoraPrint=xm_log_get('sede_generales');var xcuentaSeccionesImpresas=0;var xCuentaImpresorasEvaluadas=0;const num_copias_all=xImpresoraPrint[0].num_copias;const var_size_font_tall_comanda=xImpresoraPrint[0].var_size_font_tall_comanda;const isPrintPedidoDeliveryCompleto=xImpresoraPrint[0].isprint_all_delivery.toString()==='1';xArrayEnca.is_print_subtotales=xImpresoraPrint[0].isprint_subtotales_comanda;xArrayEnca.isprint_copy_short=xImpresoraPrint[0].isprint_copy_short;xArrayEnca.isprint_all_short=xImpresoraPrint[0].isprint_all_short;xArrayCuerpo=xArrayCuerpo.filter(x=>x);if(xPrintLocal!=undefined&&xPrintLocal!=''){xPrintLocal=$.parseJSON(xPrintLocal);xArmarSubtotalesArray(xArrayCuerpo,xImpresoraPrint)
xImpresoraPrint[0].ip_print=xPrintLocal.ip;xImpresoraPrint[0].var_margen_iz=xPrintLocal.var_margen_iz;xImpresoraPrint[0].var_size_font=xPrintLocal.var_size_font;xImpresoraPrint[0].local=1;xImpresoraPrint[0].num_copias=xPrintLocal.num_copias;xImpresoraPrint[0].copia_local=xPrintLocal.copia_local;xImpresoraPrint[0].img64=xPrintLocal.img64;xImpresoraPrint[0].papel_size=xPrintLocal.papel_size;if(xPrintLocal.img64==="0"){xImpresoraPrint[0].logo64='';}
if(parseInt(xPrintLocal.num_copias)!=0||parseInt(xPrintLocal.copia_local)!=0){xImprimirComandaAhora(xArrayEnca,xImpresoraPrint,xArrayCuerpo,xArraySubTotales,(res)=>{callback(res);});}}
let isTpcPrinter=false;let listTPCPrinter=xm_log_get('estructura_pedido');listTPCPrinter=listTPCPrinter.filter(p=>p.idimpresora!=='0');isTpcPrinter=listTPCPrinter.length>0;if(isTpcPrinter){listTPCPrinter.map(p=>{const _tpcPrint=p.idtipo_consumo;xIdPrint=p.idimpresora;xArrayBodyPrint=[];for(var i=0;i<xArrayCuerpo.length;i++){if(xArrayCuerpo[i]==null){continue;}
if(parseInt(_tpcPrint)==parseInt(xArrayCuerpo[i].id)){$.map(xArrayCuerpo[i],function(xn_p,z){if(typeof xn_p=="object"){if(xArrayBodyPrint[i]===undefined){xArrayBodyPrint[i]={'des':xArrayCuerpo[i].des,'id':xArrayCuerpo[i].id,'titlo':xArrayCuerpo[i].titulo};}
xArrayBodyPrint[i][xn_p.iditem]=xn_p;xArrayCuerpo[i].flag_add_tpc=true;}});}}
if(xArrayBodyPrint.length==0){return;}
xcuentaSeccionesImpresas++;xArmarSubtotalesArray(xArrayBodyPrint,xImpresoraPrint)
const _xArrayImpresoras=xArrayImpresoras.filter(pp=>parseInt(pp.idimpresora)==xIdPrint)[0];xImpresoraPrint[0].ip_print=_xArrayImpresoras.ip;xImpresoraPrint[0].var_margen_iz=_xArrayImpresoras.var_margen_iz;xImpresoraPrint[0].var_size_font=_xArrayImpresoras.var_size_font;xImpresoraPrint[0].local=0;xImpresoraPrint[0].num_copias=_xArrayImpresoras.num_copias;xImpresoraPrint[0].var_size_font_tall_comanda=var_size_font_tall_comanda;xImpresoraPrint[0].copia_local=0;xImpresoraPrint[0].img64=_xArrayImpresoras.img64;xImpresoraPrint[0].papel_size=_xArrayImpresoras.papel_size;if(_xArrayImpresoras.img64==="0"){xImpresoraPrint[0].logo64='';}
xImprimirComandaAhora(xArrayEnca,xImpresoraPrint,xArrayBodyPrint,xArraySubTotales,function(rpt_print_tpc){callback(rpt_print_tpc);});});}
for(var z=0;z<xArrayImpresoras.length;z++){xIdPrint=xArrayImpresoras[z].idimpresora;xArrayBodyPrint=[];xCuentaImpresorasEvaluadas++;for(var i=0;i<xArrayCuerpo.length;i++){if(xArrayCuerpo[i]==null){continue;}
$.map(xArrayCuerpo[i],function(xn_p,z){const isPedidoDelivery=xArrayCuerpo[i].des.toLowerCase()==='delivery';if(typeof xn_p=="object"){if(xArrayCuerpo[i].flag_add_tpc)return;if(xn_p.imprimir_comanda==='0')return;if(xIdPrint==xn_p.idimpresora){if(xArrayBodyPrint[i]===undefined){xArrayBodyPrint[i]={'des':xArrayCuerpo[i].des,'id':xArrayCuerpo[i].id,'titlo':xArrayCuerpo[i].titulo};}
if(isPedidoDelivery&&isPrintPedidoDeliveryCompleto){Object.values(xArrayCuerpo[i]).filter(x=>typeof x==='object').map(x=>xArrayBodyPrint[i][x.iditem]=x);}else{xArrayBodyPrint[i][xn_p.iditem]=xn_p;}}
if(xIdPrint.toString()==xn_p.idimpresora_otro.toString()){if(xArrayBodyPrint[i]===undefined){xArrayBodyPrint[i]={'des':xArrayCuerpo[i].des,'id':xArrayCuerpo[i].id,'titlo':xArrayCuerpo[i].titulo};}
if(isPedidoDelivery&&isPrintPedidoDeliveryCompleto){Object.values(xArrayCuerpo[i]).filter(x=>typeof x==='object').map(x=>xArrayBodyPrint[i][x.iditem]=x);}else{xArrayBodyPrint[i][xn_p.iditem]=xn_p;}}}})}
if(xArrayBodyPrint.length==0){continue}
xcuentaSeccionesImpresas++;xArmarSubtotalesArray(xArrayBodyPrint,xImpresoraPrint)
xImpresoraPrint[0].ip_print=xArrayImpresoras[z].ip;xImpresoraPrint[0].var_margen_iz=xArrayImpresoras[z].var_margen_iz;xImpresoraPrint[0].var_size_font=xArrayImpresoras[z].var_size_font;xImpresoraPrint[0].local=0;xImpresoraPrint[0].num_copias=xArrayImpresoras[z].num_copias;xImpresoraPrint[0].var_size_font_tall_comanda=var_size_font_tall_comanda;xImpresoraPrint[0].copia_local=0;xImpresoraPrint[0].img64=xArrayImpresoras[z].img64;xImpresoraPrint[0].papel_size=xArrayImpresoras[z].papel_size;if(xArrayImpresoras[z].img64==="0"){xImpresoraPrint[0].logo64='';}
xImprimirComandaAhora(xArrayEnca,xImpresoraPrint,xArrayBodyPrint,xArraySubTotales,function(rpt_print){if(xArrayImpresoras.length==xCuentaImpresorasEvaluadas&&rpt_print==false){if(callback){callback(false);};}
else{if(callback){callback(true);}}});};if(xcuentaSeccionesImpresas===0){if(callback){callback(false)};}}
function xImprimirComandaAhora(xArrayEncabezado,xImpresoraPrint,xArrayCuerpo,xArraySubtotal,callback){xPopupLoad.titulo="Imprimiendo...";const _sys_local=parseInt(xm_log_get('datos_org_sede')[0].sys_local);xArrayEncabezado.nom_us=xm_log_get('app3_us').nomus;const _data={Array_enca:xArrayEncabezado,Array_print:xImpresoraPrint,ArrayItem:xArrayCuerpo.filter(x=>!null),ArraySubTotales:xArraySubtotal}
if(_sys_local===1){xSendDataPrintServer(_data,1,'comanda');setTimeout(()=>{callback(false);},300);return;}
$.ajax({type:'POST',url:'../../print/print3.php',data:{Array_enca:xArrayEncabezado,Array_print:xImpresoraPrint,ArrayItem:xArrayCuerpo,ArraySubTotales:xArraySubtotal},success:function(dtPbd){if(dtPbd.indexOf('Error')!=-1){xPopupLoad.xclose();$("#print_error").text(dtPbd);xErrorPrint=true;}else{xErrorPrint=false;xPopupLoad.titulo="Imprimiendo...";xPopupLoad.xopen();setTimeout(function(){xPopupLoad.xclose()},3000);}
callback(xErrorPrint);},error:function(XMLHttpRequest,textStatus,errorThrown){console.log(errorThrown);xPopupLoad.xclose();$("#print_error").text("Error, Verifique que la ticketera este prendida y que tenga papel.");xErrorPrint=true;callback(xErrorPrint);}});}
function xImprimirCualquierLista(dataToPrinter,idestructura=5,nomfile='listado'){xPopupLoad.titulo="Imprimiendo...";xPopupLoad.xopen();dataToPrinter.encabezado.nom_us=xm_log_get('app3_us').nomus;const _data={Array_enca:dataToPrinter.encabezado,Array_print:dataToPrinter.impresora,ArrayItem:dataToPrinter.lista,ArraySubTotales:dataToPrinter.subtotales}
xSendDataPrintServer(_data,idestructura,nomfile);setTimeout(()=>{xPopupLoad.xclose();},300);}
function xSendDataPrintServer(_data,_idprint_server_estructura,_tipo){switch(_idprint_server_estructura){case 3:break;case 4:if(_data.Array_enca[0].ip_print==='')return;break;default:try{if(_data.Array_print[0].ip_print==='')return;_data.Array_print[0].logo64='';_data.Array_print[0].logo='';}catch(error){}
break;}
_data=JSON.stringify(_data);_tipo=_tipo==='pre cuenta'?'comanda':_tipo;$.ajax({url:'../../bdphp/log_003.php?op=1',type:'POST',data:{datos:_data,idprint_server_estructura:_idprint_server_estructura,tipo:_tipo}}).done((UltimoIdPrint)=>{var dataSend={detalle_json:_data,idprint_server_estructura:_idprint_server_estructura,tipo:_tipo,descripcion_doc:_tipo,nom_documento:_tipo,idprint_server_detalle:UltimoIdPrint}
_cpSocketEmitPrinterOnly(dataSend);}).fail(function(e){alert("error",e);console.log('error',e);});}
function xReturnCorrelativoComprobante(_obj){let _rpt;if(_obj.codsunat==='0'){_rpt=parseInt(_obj.correlativo)+1;_rpt=xCeroIzq(_rpt,7);$.ajax({type:'POST',url:'../../bdphp/log_002.php',data:{op:'103',i:_obj.idtipo_comprobante_serie}});}else{const tomaDelApi=parseInt(_obj.facturacion_correlativo_api)===0?false:true;_rpt=tomaDelApi?'#':parseInt(_obj.correlativo)+1;if(!tomaDelApi){_obj.facturacion_correlativo_api=1;}}
return _rpt;}
function xUpdatePrintPrecuentaPedido(_id){$.ajax({url:'../../bdphp/log_003.php?op=6',type:'POST',data:{id:_id}});}
async function xGetCorrelativoComprobante(_obj){const result=await $.ajax({type:'POST',url:'../../bdphp/log_002.php',data:{op:'103001',i:_obj.idtipo_comprobante_serie,obj:_obj}})
const rpt=JSON.parse(result)
if(rpt.success){return rpt.datos[0].num;}else{return'#';}}
function comprobarNumCorrelativoComprobante(xArrayComprobante){console.log('numero en comprobancion A',xArrayComprobante.correlativo);const _numIntCorrelativo=parseInt(xArrayComprobante.correlativo);const _isNotIntNumComprobante=isNaN(_numIntCorrelativoBD);if(_isNotIntNumComprobante){xArrayComprobante.correlativo=_numIntCorrelativoBD;console.log('numero en comprobancion B',xArrayComprobante.correlativo)}}
function getImpresoraByTpc(idtipo_consumo){const listTPCPrinter=xm_log_get('estructura_pedido');let xArrayImpresoras=xm_log_get('app3_woIpPrint')
let printSelected=null
const _tpcPrint=listTPCPrinter.filter(p=>parseInt(p.idtipo_consumo)==idtipo_consumo)[0];if(_tpcPrint){if(_tpcPrint.idimpresora!=='0'){printSelected=xArrayImpresoras.filter(p=>parseInt(p.idimpresora)==_tpcPrint.idimpresora)[0];}}
return printSelected?printSelected:false;}
function getImpresoraByIdImpresoraSeccion(idimpresora_seccion){let xArrayImpresoras=xm_log_get('app3_woIpPrint')
const printSelected=xArrayImpresoras.filter(p=>parseInt(p.idimpresora)==parseInt(idimpresora_seccion))[0];return printSelected?printSelected:false;}
function cocinarImpresionAnulacionOne(dataItem,usuarioSupervisor,usuarioCaja,infoDataPedido){console.log('dataItem',dataItem);let printer;printer=getImpresoraByTpc(dataItem.idtipoconsumo);console.log('printer',printer);if(!printer){printer=getImpresoraByIdImpresoraSeccion(dataItem.idimpresora_seccion);}
if(!printer)return;let _listaItemAnulados=[];const des_tpc=dataItem.des_tp.toUpperCase();const des_item=dataItem.descripcion.toUpperCase();const des_mesa=infoDataPedido.nummesa==="0"?`PEDIDO ${infoDataPedido.numpedido}`:`MESA ${infoDataPedido.nummesa}`;const infoUsuario=`Caja:${usuarioCaja}-Supervisor:${usuarioSupervisor}`_listaItemAnulados.push({descripcion:des_item.toUpperCase(),cantidad:'01',});printer.ip_print=printer.ip;const _dataPrintD={lista:_listaItemAnulados,impresora:[printer],subtotales:[],encabezado:{titulo:'ANULACION',tipo_consumo:des_tpc,mesa:des_mesa,correlativo_lista:0,usuario:infoUsuario,motivo:''}}
console.log('lista anulacion',_dataPrintD);xImprimirCualquierLista(_dataPrintD);}
function cocinarImpresionAnulacionList(listItemsAnular,usuarioSupervisor,usuarioCaja,infoDataPedido,motivoAnulacion){console.log('dataItem',listItemsAnular);let listItemAgrupados=[]
listItemsAnular.map(x=>{let printer;printer=getImpresoraByTpc(x.idtipoconsumo);if(!printer)return;printer.ip_print=printer.ip;const _isTpc=listItemAgrupados.filter(p=>p.idtipoconsumo===x.idtipoconsumo)[0];if(_isTpc){const rowAdd={descripcion:x.descripcion,cantidad:xCeroIzq(x.cant_item,2),}
_isTpc.items.push(rowAdd);}else{let listAdd=[]
const rowAdd={descripcion:x.descripcion,cantidad:xCeroIzq(x.cant_item,2),}
listAdd.push(rowAdd)
listItemAgrupados.push({idtipoconsumo:x.idtipoconsumo,idseccion:0,des_tpc:x.des_tp,printer:printer,items:listAdd})}
x.chekPrint=true;})
listItemsAnular.map(x=>{if(x.chekPrint)return false
let printer;printer=getImpresoraByIdImpresoraSeccion(x.idimpresora_seccion);if(!printer)return;printer.ip_print=printer.ip;const _isTpc=listItemAgrupados.filter(p=>p.idseccion===x.idseccion)[0];if(_isTpc){const rowAdd={descripcion:x.descripcion,cantidad:xCeroIzq(x.cant_item,2),}
_isTpc.items.push(rowAdd);}else{let listAdd=[]
const rowAdd={descripcion:x.descripcion,cantidad:xCeroIzq(x.cant_item,2)}
listAdd.push(rowAdd)
listItemAgrupados.push({idtipoconsumo:0,idseccion:x.idseccion,des_tpc:x.des_tp,printer:printer,items:listAdd})}})
console.log('listItemAgrupados',listItemAgrupados);if(listItemAgrupados.length===0)return false;const des_mesa=infoDataPedido.nummesa==="0"?`PEDIDO ${infoDataPedido.numpedido}`:`MESA ${infoDataPedido.nummesa}`;const infoUsuario=`Caja:${usuarioCaja}-Supervisor:${usuarioSupervisor}`listItemAgrupados.map(x=>{const _dataPrintD={lista:x.items,impresora:[x.printer],subtotales:[],encabezado:{titulo:'ANULACION',tipo_consumo:x.des_tpc,mesa:des_mesa,correlativo_lista:0,usuario:infoUsuario,motivo:motivoAnulacion.toUpperCase()}}
console.log('lista anulacion',_dataPrintD);xImprimirCualquierLista(_dataPrintD);})}