var comprobantdoConexion=false;var restaurandoConexion=false;var connection,type;try{connection=navigator.connection||navigator.mozConnection||navigator.webkitConnection;type=connection.effectiveType;connection.addEventListener('change',activarChangeConection);}catch(error){}
var _num_intentos_conexion=0;window.addEventListener("focus",function(event){console.log('focus windows');const _now_date=new Date();const _date_bk=new Date(getLocalStorage('::app3_sys_backup_time'));const _minDiff=Math.round((_now_date.getTime()-_date_bk.getTime())/60000);if(_minDiff<3)return;setTimeout(()=>{updateConnectionStatusFocus();},3000);});$(window).blur(function(){console.log('blur');bkLocalStorage();})
async function updateConnectionStatusFocus(){var rpt_conex=await comprobarConexion();if(rpt_conex){const _data_res=xm_log_get('app3_us')._sys_sessid;const _restore_conex=await restoreConexion(_data_res);if(_restore_conex){resotreLocalSotrage();xm_all_xToastOpen('Verificando conexion',2000);console.log('restablecio la conexion focus');}}}
async function updateConnectionStatus(){if(_num_intentos_conexion>1){_num_intentos_conexion=0;return;}
if(!comprobantdoConexion){const _sys_no_conect=getLocalStorage('::app3_sys_no_conex')||false;var rpt_conex=await comprobarConexion();if(!rpt_conex){setTimeout(()=>{_num_intentos_conexion++;updateConnectionStatus();return;},2500);}
if(!rpt_conex){console.log('estado conexion ',rpt_conex);console.log('localstorage -> ',(getLocalStorage('::app3_woDUS')));setLocalSotrage('::app3_sys_no_conex',true);bkLocalStorage();}else{if(!_sys_no_conect)return;removeLocalStorage('::app3_sys_no_conex');const _data_res=xm_log_get('app3_us')._sys_sessid;xm_all_xToastOpen('Recuperando conexion',3000);const _restore_conex=await restoreConexion(_data_res);if(_restore_conex){resotreLocalSotrage();removeLocalStorage('::app3_sys_no_conex');}
console.log('estado conexion ',rpt_conex);}}}
function activarChangeConection(){setTimeout(()=>{updateConnectionStatus();},3000);}
async function comprobarConexion(){var rpt_conex=false;comprobantdoConexion=true;await fetch('../../bdphp/log_run.php?op=3').then(function(response){return response}).then(res=>{rpt_conex=true;}).catch(function(error){rpt_conex=false;});comprobantdoConexion=false;return rpt_conex;}
async function restoreConexion(_data){restaurandoConexion=false;await $.ajax({type:'POST',url:'../../bdphp/log.php?op=-1',data:{sys_data:_data}}).done(function(res){console.log('restaurando');restaurandoConexion=true;});return restaurandoConexion;}