var idSedeSel=0;var idComprobanteSel=0;var cnf_SedeSel;var cnf_ComprobanteSel;function config_comprobante_add(){config_comprobante_find_row();$("#form_emision_comprobante #idsede").val(idSedeSel);$("#form_emision_comprobante #idtipo_comprobante").val(idComprobanteSel);xPopupLoad.xopen();$.post("../../bdphp/ManejoBD_IUD.php?tb=tipo_comprobante_serie",$("#form_emision_comprobante").serialize(),function(a){xPopupLoad.xclose();const idorg=$("#form_emision_comprobante #idorg").val();$("#form_emision_comprobante").reset();$("#form_emision_comprobante #idorg").val(idorg);xPopupLoad.xclose();config_comprobante_getall();})}
function config_comprobante_find_row(){$("#tb_emision_comprobantes .row").each((index,element)=>{if(!element.textContent){return;}
if(element.textContent.indexOf(this.cnf_ComprobanteSel.descripcion)>-1&&element.textContent.indexOf(this.cnf_SedeSel.nombre)>-1){return;}})}
function config_comprobante_getall(){$("#tb_emision_comprobantes .row").remove();$("#tb_emision_comprobantes").append('<tr class="row"><td colspan="4"><paper-spinner active></paper-spinner></td></tr>');$.ajax({type:'POST',url:'../../bdphp/log.php?op=1607'}).done(function(dtComprobante){var xdtComprobante=$.parseJSON(dtComprobante);var xcadena_tr_comp='';xdtComprobante=xdtComprobante.datos;xdtComprobante.map(x=>{xcadena_tr_comp=String(xcadena_tr_comp+'<tr class="row" data-id="'+x.idtipo_comprobante_serie+'" data-t="tipo_comprobante_serie"><td>'+x.dsc_sede+'</td>'+'<td>'+x.dsc_comprobante+'</td>'+'<td>'+x.serie+'</td>'+'<td>'+x.correlativo+'</td>'+'<td><span class="xDeleteRow" title="Borrar" onclick="xDialogBorrarObj(this);"></span></td>'+'</tr>')})
$("#tb_emision_comprobantes .row").remove();$("#tb_emision_comprobantes").append(xcadena_tr_comp).trigger('create');});this.config_valoresInicialesComponente();}
function config_comprobante_update_token(obj){var xvalObj=$(obj).val(),xid_row=$(obj).parents('.row').attr('data-id'),xcampo_row=$(obj).parent().attr('data-campo');$.ajax({type:'POST',url:'../../bdphp/log.php?op=2108',data:{campo:xcampo_row,valor:xvalObj,id:xid_row}}).done(function(dtPrint){if(dtPrint.indexOf('Error')!=-1){alert(dtPrint)}})}
function config_comprobante_update_id(obj){var xvalObj=$(obj).val(),xid_row=$(obj).parents('.row').attr('data-id'),xcampo_row=$(obj).parent().attr('data-campo');$.ajax({type:'POST',url:'../../bdphp/log.php?op=2108',data:{campo:xcampo_row,valor:xvalObj,id:xid_row}}).done(function(dtPrint){if(dtPrint.indexOf('Error')!=-1){alert(dtPrint)}})}
function _getSede($event){this.cnf_SedeSel=$event;this.idSedeSel=$event.idsede;}
function _getComprobante($event){this.cnf_ComprobanteSel=$event;this.idComprobanteSel=$event.idtipo_comprobante;}
function config_valoresInicialesComponente(){this.cnf_SedeSel=$("#compFindSede")[0].__data__.sedes;this.cnf_ComprobanteSel=$("#compFindComprobante")[0].__data__.comprobantes;this.idSedeSel=cnf_SedeSel.idsede;this.idComprobanteSel=cnf_ComprobanteSel.idtipo_comprobante;}